### USER LOGIN SHOULD RETURN A JWT TOKEN 
 POST  http://localhost:5443/users/login HTTP/1.1
content-type: application/json

{
    "email": "dude@sschilling.com",
    "password": "dude"
    
}

### ADD USER 
POST  http://localhost:5443/users/signup
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImR1ZGVAc3NjaGlsbGluZy5jb20iLCJ1c2VySWQiOiI2MDgzMGY0NmM5N2M2MjY2NTg2ZjM5ODAiLCJpYXQiOjE2MjIyMjkxMTUsImV4cCI6MTYyMjIzMjcxNX0.3DN7Hiat_9jbWhMrutCFhzhi68cijiFn4SEBdUM5H30
content-type: application/json

{
    "email": "dude7@dude.com",
    "password": "dude"
    
}

### DELETE A USER 
DELETE  https://localhost:5443/users/6086007bbd461dbfd38222bc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImR1ZGVAc3NjaGlsbGluZy5jb20iLCJ1c2VySWQiOiI2MDgzMGY0NmM5N2M2MjY2NTg2ZjM5ODAiLCJpYXQiOjE2MjE4Njc0MDYsImV4cCI6MTYyMTg3MTAwNn0.wCAQs9WoxgQ_E6g4qYJYym-_n8p5fIbXe9JpEqsJ3eM
### GET REQUEST FOR SINGLE HAPPY RECORD
GET  https://localhost:5443/happy/6082de6f6e15435dc84765a5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImR1ZGVAc3NjaGlsbGluZy5jb20iLCJ1c2VySWQiOiI2MDgzMGY0NmM5N2M2MjY2NTg2ZjM5ODAiLCJpYXQiOjE2MjE4ODI5NTEsImV4cCI6MTYyMTg4NjU1MX0.gm0w2VBOxePPh3d98QFx2zZ30JHqcBRIZKQFcSG1JGE


### GET REQUEST THAT RETURNS ALL  HAPPY RECORDS 
GET http://localhost:5443/happy/
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImR1ZGVAc3NjaGlsbGluZy5jb20iLCJ1c2VySWQiOiI2MDgzMGY0NmM5N2M2MjY2NTg2ZjM5ODAiLCJpYXQiOjE2MjIzOTY4OTAsImV4cCI6MTYyMjQwMDQ5MH0.lhhnJ2ziF8L7CdOtrrGdRYbLQ3dUAgfjSpdZbyFPFPA
### POST REQUEST TO ADD A SINGLE HAPPY RECORD 
POST http://localhost:5443/happy/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImR1ZGVAc3NjaGlsbGluZy5jb20iLCJ1c2VySWQiOiI2MDgzMGY0NmM5N2M2MjY2NTg2ZjM5ODAiLCJpYXQiOjE2MjQ2NDMyMjQsImV4cCI6MTYyNDY0NjgyNH0.qjYvs8PWZdHa6fxiaGE79zqbCESxcEPA0vuKTEql8pw
content-type: application/json

{
    "happyScore": "4",
    "sleepHours": "12",
    "kindness": "true",
    "exercise": "true",
    "exerciseLevel": "high",
    "kindnessNote": "doing some random act of kindness feel great!",
    "gratitudeNote": "Loving IT!"
} 

### UPDATE A HAPPINESS RECORD 
PATCH https://localhost:5443/happy/60abb862749a3d0d5360cfd3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImR1ZGVAc3NjaGlsbGluZy5jb20iLCJ1c2VySWQiOiI2MDgzMGY0NmM5N2M2MjY2NTg2ZjM5ODAiLCJpYXQiOjE2MjE4Njk4MTYsImV4cCI6MTYyMTg3MzQxNn0.A9DCyGfEczO3AHZ9qfoNpw4SUoy7Ejz7wmpDSts5TFk
content-type: application/json

[
    {
        "propName":"sleepHours",
    "value": "10"
    }
]

### DELETE A SINGLE HAPPY RECORD 
DELETE  https://localhost:5443/happy/60abb813f1de790d05d01d08
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImR1ZGVAc3NjaGlsbGluZy5jb20iLCJ1c2VySWQiOiI2MDgzMGY0NmM5N2M2MjY2NTg2ZjM5ODAiLCJpYXQiOjE2MjE4NjYyNzUsImV4cCI6MTYyMTg2OTg3NX0.hYISe8m4Nsc2hYGsKlG-VEPdDDPtuqLoQ07rfzdrw3I




